// Friends system — data layer.
//
// Adding an AI / curated "top player" (short static ids, no real device behind
// them) is instant and purely local. Adding a REAL player (device id starting
// with "d_") sends a genuine friend request through Supabase; the recipient
// polls for it, accepts, and both sides end up with each other as a friend.
// Sending a gift to a real friend writes a row the recipient claims from their
// Inbox — there is no "collect" action inside the Friends list itself.
import { supabase } from './supabaseClient';
import { fetchTopPlayers, getDeviceId, LeaderboardEntry, LocalPlayer } from './leaderboardService';
import { Friend } from '../types';

export const DAILY_MS = 24 * 60 * 60 * 1000;

// Real players have a device id generated by getDeviceId() ("d_..."); AI / seed
// leaderboard rows use short static ids ("s1".."s20", "x1".."x52") and have no
// device on the other end to receive requests or gifts.
export const isRealPlayerId = (id: string): boolean => id.startsWith('d_');

// Players you can still add — real devices only. AI/seed board entries have no
// device on the other end, so a request to one can never be accepted; keeping
// them out of search avoids the confusing "sent but never accepted" dead end.
export async function getAddablePlayers(you: LocalPlayer, existingIds: string[]): Promise<LeaderboardEntry[]> {
    const board = await fetchTopPlayers(you, 'score');
    const existing = new Set(existingIds);
    return board.filter(e => !e.isYou && !existing.has(e.id) && isRealPlayerId(e.id));
}

export function toFriend(e: LeaderboardEntry, now: number): Friend {
    return { id: e.id, name: e.name, avatar: e.avatar, level: e.level, isAI: !isRealPlayerId(e.id), addedAt: now };
}

export function canSend(friend: Friend, now: number): boolean {
    return !friend.lastSentAt || now - friend.lastSentAt >= DAILY_MS;
}
export function nextResetIn(timestamp: number | undefined, now: number): number {
    if (!timestamp) return 0;
    return Math.max(0, DAILY_MS - (now - timestamp));
}

// A received gift is always worth 3x the RECIPIENT's own max bet — computed on
// their side when the message is created, not baked in by the sender.
export const receivedGiftAmount = (recipientMaxBet: number) => Math.round(recipientMaxBet * 3);

// ---- Friend requests (real players only) ----

export interface IncomingRequest {
    id: number;
    fromDevice: string;
    fromName: string;
    fromAvatar: string;
    fromLevel: number;
    createdAt: number;
}

export async function sendFriendRequest(you: LocalPlayer, toDeviceId: string): Promise<boolean> {
    if (!supabase) return false;
    try {
        const { error } = await supabase.from('friend_requests').insert({
            from_device: getDeviceId(),
            to_device: toDeviceId,
            from_name: you.name || 'Player',
            from_avatar: you.avatar || '',
            from_level: you.level,
        });
        if (error) { console.warn('[friends] request send failed — run supabase/friends.sql?', error.message); return false; }
        return true;
    } catch (e) {
        console.warn('[friends] request send failed — run supabase/friends.sql?', e);
        return false;
    }
}

export async function fetchIncomingRequests(): Promise<IncomingRequest[]> {
    if (!supabase) return [];
    try {
        const { data, error } = await supabase.from('friend_requests').select('*')
            .eq('to_device', getDeviceId()).eq('status', 'pending');
        if (error || !data) return [];
        return data.map((r: any) => ({
            id: r.id, fromDevice: r.from_device, fromName: r.from_name || 'Player',
            fromAvatar: r.from_avatar || '/Profile_pic (3).png', fromLevel: r.from_level ?? 1,
            createdAt: new Date(r.created_at).getTime(),
        }));
    } catch {
        return [];
    }
}

export async function acceptFriendRequest(requestId: number): Promise<void> {
    if (!supabase) return;
    try { await supabase.from('friend_requests').update({ status: 'accepted' }).eq('id', requestId); } catch {}
}

export interface AcceptedForSender {
    id: number;
    toDevice: string;
    toName: string;
    toAvatar: string;
    toLevel: number;
}

// Requests you sent that the other side has since accepted — pick these up so
// you also gain the friend locally, then mark them acknowledged so they're
// only processed once.
export async function fetchAcceptedForSender(): Promise<AcceptedForSender[]> {
    if (!supabase) return [];
    try {
        const me = getDeviceId();
        const { data, error } = await supabase.from('friend_requests').select('*')
            .eq('from_device', me).eq('status', 'accepted').eq('sender_ack', false);
        if (error || !data || data.length === 0) return [];
        // Look up each recipient's current profile from the leaderboard table.
        const toDevices = data.map((r: any) => r.to_device);
        const { data: profiles } = await supabase.from('leaderboard').select('*').in('device_id', toDevices);
        const byId = new Map((profiles || []).map((p: any) => [p.device_id, p]));
        return data.map((r: any) => {
            const p = byId.get(r.to_device);
            return {
                id: r.id, toDevice: r.to_device,
                toName: p?.name || 'Player', toAvatar: p?.avatar || '/Profile_pic (3).png', toLevel: p?.level ?? 1,
            };
        });
    } catch {
        return [];
    }
}

export async function ackSenderRequest(requestId: number): Promise<void> {
    if (!supabase) return;
    try { await supabase.from('friend_requests').update({ sender_ack: true }).eq('id', requestId); } catch {}
}

// ---- Gifting (real players only) ----
// The gift row just records who sent it — the recipient computes their own
// reward (3x their own max bet) client-side when they see it, so the amount
// always reflects the RECEIVER's progression, not the sender's.

export async function sendGiftToFriend(you: LocalPlayer, toDeviceId: string): Promise<boolean> {
    if (!supabase) return false;
    try {
        const { error } = await supabase.from('friend_gifts').insert({
            from_device: getDeviceId(), to_device: toDeviceId, from_name: you.name || 'Player',
        });
        if (error) { console.warn('[friends] gift send failed — run supabase/friends.sql?', error.message); return false; }
        return true;
    } catch (e) {
        console.warn('[friends] gift send failed — run supabase/friends.sql?', e);
        return false;
    }
}

export interface IncomingGift {
    id: number;
    fromDevice: string;
    fromName: string;
    createdAt: number;
}

export async function fetchIncomingGifts(): Promise<IncomingGift[]> {
    if (!supabase) return [];
    try {
        const { data, error } = await supabase.from('friend_gifts').select('*')
            .eq('to_device', getDeviceId()).eq('claimed', false);
        if (error || !data) return [];
        return data.map((r: any) => ({ id: r.id, fromDevice: r.from_device, fromName: r.from_name || 'A friend', createdAt: new Date(r.created_at).getTime() }));
    } catch {
        return [];
    }
}

export async function markGiftClaimed(giftId: number): Promise<void> {
    if (!supabase) return;
    try { await supabase.from('friend_gifts').update({ claimed: true }).eq('id', giftId); } catch {}
}
